import {
  AlertCircle,
  Briefcase,
  Building2,
  CheckCircle2,
  Circle,
  Clock,
  ListTodo,
  Loader,
  User,
} from "lucide-react";
import type {
  OverdueTask,
  TaskMetric,
  TaskPrioritySegment,
  TaskRecord,
  TaskSummaryStats,
  UpcomingTask,
} from "./types";

export const TASK_METRICS: TaskMetric[] = [
  {
    id: "total",
    label: "Total Tasks",
    value: 34,
    trend: 16,
    trendDirection: "up",
    trendLabel: "vs last month",
    icon: ListTodo,
    iconBg: "#ede9fe",
    iconColor: "#7c3aed",
  },
  {
    id: "todo",
    label: "To Do",
    value: 12,
    trend: 8,
    trendDirection: "up",
    trendLabel: "vs last month",
    icon: Circle,
    iconBg: "#dbeafe",
    iconColor: "#3b82f6",
  },
  {
    id: "in-progress",
    label: "In Progress",
    value: 8,
    trend: 5,
    trendDirection: "down",
    trendLabel: "vs last month",
    icon: Loader,
    iconBg: "#ffedd5",
    iconColor: "#f97316",
  },
  {
    id: "completed",
    label: "Completed",
    value: 14,
    trend: 22,
    trendDirection: "up",
    trendLabel: "vs last month",
    icon: CheckCircle2,
    iconBg: "#dcfce7",
    iconColor: "#22c55e",
  },
  {
    id: "overdue",
    label: "Overdue",
    value: 4,
    trend: 5,
    trendDirection: "down",
    trendLabel: "vs last month",
    icon: AlertCircle,
    iconBg: "#fee2e2",
    iconColor: "#ef4444",
  },
];

export const TASK_RECORDS: TaskRecord[] = [
  {
    id: "1",
    title: "Send proposal to Ubiquitous",
    description: "WhatsApp Agent pitch follow-up",
    associatedName: "Ubiquitous",
    associatedType: "agency",
    assigneeName: "Sajam J.",
    assigneeInitials: "SJ",
    dueDate: "Today",
    dueTime: "3:00 PM",
    dueLabel: "Today",
    isDueUrgent: true,
    priority: "High",
    status: "To Do",
  },
  {
    id: "2",
    title: "Schedule demo with John Smith",
    description: "Luxury Property Campaign walkthrough",
    associatedName: "John Smith",
    associatedType: "contact",
    assigneeName: "Sajam J.",
    assigneeInitials: "SJ",
    dueDate: "Today",
    dueTime: "2:00 PM",
    dueLabel: "Today",
    isDueUrgent: true,
    priority: "High",
    status: "In Progress",
  },
  {
    id: "3",
    title: "Review contract terms",
    description: "Viral Nation enterprise agreement",
    associatedName: "Viral Nation",
    associatedType: "agency",
    assigneeName: "Alex M.",
    assigneeInitials: "AM",
    dueDate: "Tomorrow",
    dueTime: "11:00 AM",
    dueLabel: "Tomorrow",
    isDueUrgent: false,
    priority: "Medium",
    status: "To Do",
  },
  {
    id: "4",
    title: "Update pitch deck for TikTok",
    description: "Creator outreach automation features",
    associatedName: "TikTok Automation",
    associatedType: "campaign",
    assigneeName: "Sajam J.",
    assigneeInitials: "SJ",
    dueDate: "Jul 3, 2025",
    dueTime: "5:00 PM",
    isDueUrgent: false,
    priority: "Medium",
    status: "In Progress",
  },
  {
    id: "5",
    title: "Follow up on overdue payment",
    description: "Influencer pilot program invoice",
    associatedName: "Influencer Deal",
    associatedType: "deal",
    assigneeName: "Alex M.",
    assigneeInitials: "AM",
    dueDate: "Jun 28, 2025",
    dueTime: "—",
    isDueUrgent: true,
    priority: "High",
    status: "Overdue",
  },
  {
    id: "6",
    title: "Prepare Q3 outreach report",
    description: "Monthly agency performance summary",
    associatedName: "House of Marketers",
    associatedType: "agency",
    assigneeName: "Sajam J.",
    assigneeInitials: "SJ",
    dueDate: "Jul 5, 2025",
    dueTime: "12:00 PM",
    isDueUrgent: false,
    priority: "Low",
    status: "To Do",
  },
  {
    id: "7",
    title: "Send onboarding materials",
    description: "The Goat Agency new client setup",
    associatedName: "The Goat Agency",
    associatedType: "agency",
    assigneeName: "Alex M.",
    assigneeInitials: "AM",
    dueDate: "Jun 25, 2025",
    dueTime: "—",
    isDueUrgent: false,
    priority: "Low",
    status: "Completed",
  },
  {
    id: "8",
    title: "Call Nick Cooke re: contract",
    description: "Final terms negotiation",
    associatedName: "Nick Cooke",
    associatedType: "contact",
    assigneeName: "Sajam J.",
    assigneeInitials: "SJ",
    dueDate: "Jun 27, 2025",
    dueTime: "10:00 AM",
    isDueUrgent: true,
    priority: "High",
    status: "Overdue",
  },
];

export const TASK_PRIORITY_SUMMARY: TaskPrioritySegment[] = [
  { label: "High", value: 12, color: "#ef4444" },
  { label: "Medium", value: 15, color: "#f97316" },
  { label: "Low", value: 7, color: "#22c55e" },
];

export const UPCOMING_TASKS: UpcomingTask[] = [
  { id: "1", title: "Schedule demo with John Smith", time: "Today, 2:00 PM" },
  { id: "2", title: "Send proposal to Ubiquitous", time: "Today, 3:00 PM" },
  { id: "3", title: "Review contract terms", time: "Tomorrow, 11:00 AM" },
];

export const OVERDUE_TASKS: OverdueTask[] = [
  { id: "1", title: "Follow up on overdue payment", dueDate: "Jun 28, 2025" },
  { id: "2", title: "Call Nick Cooke re: contract", dueDate: "Jun 27, 2025" },
  { id: "3", title: "Send rate card to Ben Jeffries", dueDate: "Jun 26, 2025" },
];

export const TASK_SUMMARY_STATS: TaskSummaryStats = {
  created: 45,
  completed: 28,
  completionRate: 62,
};

export const ASSOCIATED_ICONS = {
  agency: Building2,
  contact: User,
  deal: Briefcase,
  campaign: Clock,
} as const;

export const SORT_OPTIONS = [
  { value: "newest", label: "Newest First" },
  { value: "oldest", label: "Oldest First" },
  { value: "due-date", label: "Due Date" },
  { value: "priority", label: "Priority" },
] as const;
