import {
  AlertCircle,
  Calendar,
  CheckCircle2,
  Clock,
  Hourglass,
  Mail,
  MessageCircle,
  Phone,
  Reply,
  Timer,
} from "lucide-react";
import type {
  FollowUpMetric,
  FollowUpRecord,
  FollowUpSummarySegment,
  SmartSuggestion,
  UpcomingFollowUp,
} from "./types";

export const FOLLOW_UP_METRICS: FollowUpMetric[] = [
  {
    id: "total",
    label: "Total Follow Ups",
    value: 86,
    trend: 14,
    trendDirection: "up",
    trendLabel: "vs last month",
    icon: Clock,
    iconBg: "#ede9fe",
    iconColor: "#7c3aed",
  },
  {
    id: "due-today",
    label: "Due Today",
    value: 12,
    trend: 20,
    trendDirection: "down",
    trendLabel: "vs last month",
    icon: Calendar,
    iconBg: "#fee2e2",
    iconColor: "#ef4444",
  },
  {
    id: "due-week",
    label: "Due This Week",
    value: 24,
    trend: 8,
    trendDirection: "up",
    trendLabel: "vs last month",
    icon: Hourglass,
    iconBg: "#ffedd5",
    iconColor: "#f97316",
  },
  {
    id: "completed",
    label: "Completed",
    value: 38,
    trend: 18,
    trendDirection: "up",
    trendLabel: "vs last month",
    icon: CheckCircle2,
    iconBg: "#dcfce7",
    iconColor: "#22c55e",
  },
  {
    id: "overdue",
    label: "Overdue",
    value: 7,
    trend: 12,
    trendDirection: "down",
    trendLabel: "vs last month",
    icon: AlertCircle,
    iconBg: "#fee2e2",
    iconColor: "#ef4444",
  },
];

export const FOLLOW_UP_RECORDS: FollowUpRecord[] = [
  {
    id: "1",
    contactName: "Matt Ziel",
    contactTitle: "CEO",
    initials: "MZ",
    agency: "Ubiquitous",
    campaign: "WhatsApp Agent Pitch",
    nextFollowUp: "Today",
    nextFollowUpTime: "2:00 PM",
    isUrgent: true,
    type: "WhatsApp",
    status: "Due Today",
    priority: "High",
  },
  {
    id: "2",
    contactName: "Joe Gagliese",
    contactTitle: "Co-Founder",
    initials: "JG",
    agency: "Viral Nation",
    campaign: "Rate Negotiation Demo",
    nextFollowUp: "Today",
    nextFollowUpTime: "4:30 PM",
    isUrgent: true,
    type: "Email",
    status: "Due Today",
    priority: "High",
  },
  {
    id: "3",
    contactName: "Nick Cooke",
    contactTitle: "CEO",
    initials: "NC",
    agency: "The Goat Agency",
    campaign: "Creator Outreach",
    nextFollowUp: "Tomorrow",
    nextFollowUpTime: "10:00 AM",
    isUrgent: false,
    type: "Phone Call",
    status: "Due Tomorrow",
    priority: "Medium",
  },
  {
    id: "4",
    contactName: "Inigo Rivero",
    contactTitle: "Managing Director",
    initials: "IR",
    agency: "House of Marketers",
    campaign: "TikTok Automation",
    nextFollowUp: "Jul 3, 2025",
    nextFollowUpTime: "11:00 AM",
    isUrgent: false,
    type: "WhatsApp",
    status: "Scheduled",
    priority: "Medium",
  },
  {
    id: "5",
    contactName: "Ben Jeffries",
    contactTitle: "CEO",
    initials: "BJ",
    agency: "Influencer",
    campaign: "Enterprise Pitch",
    nextFollowUp: "Jun 28, 2025",
    nextFollowUpTime: "—",
    isUrgent: true,
    type: "Email",
    status: "Overdue",
    priority: "High",
  },
  {
    id: "6",
    contactName: "Edward East",
    contactTitle: "Founder",
    initials: "EE",
    agency: "Billion Dollar Boy",
    campaign: "UGC Campaign",
    nextFollowUp: "Jul 5, 2025",
    nextFollowUpTime: "3:00 PM",
    isUrgent: false,
    type: "WhatsApp",
    status: "Scheduled",
    priority: "Low",
  },
  {
    id: "7",
    contactName: "Ann Stanley",
    contactTitle: "CEO",
    initials: "AS",
    agency: "Anicca Digital",
    campaign: "Booking Agent Intro",
    nextFollowUp: "Jun 25, 2025",
    nextFollowUpTime: "—",
    isUrgent: false,
    type: "Phone Call",
    status: "Completed",
    priority: "Low",
  },
];

export const FOLLOW_UP_SUMMARY: FollowUpSummarySegment[] = [
  { label: "Due Today", value: 28, color: "#ef4444" },
  { label: "This Week", value: 35, color: "#f97316" },
  { label: "Scheduled", value: 22, color: "#3b82f6" },
  { label: "Overdue", value: 15, color: "#dc2626" },
];

export const SMART_SUGGESTIONS: SmartSuggestion[] = [
  {
    id: "1",
    message: "3 contacts have not replied in 5+ days",
    icon: Reply,
    iconBg: "#ffedd5",
    iconColor: "#f97316",
  },
  {
    id: "2",
    message: "7 follow ups are overdue — act now",
    icon: AlertCircle,
    iconBg: "#fee2e2",
    iconColor: "#ef4444",
  },
  {
    id: "3",
    message: "Best time to reach UK agencies: 10–11 AM",
    icon: Timer,
    iconBg: "#ede9fe",
    iconColor: "#7c3aed",
  },
];

export const UPCOMING_FOLLOW_UPS: UpcomingFollowUp[] = [
  {
    id: "1",
    name: "Matt Ziel",
    initials: "MZ",
    time: "Today, 2:00 PM",
    agency: "Ubiquitous",
  },
  {
    id: "2",
    name: "Joe Gagliese",
    initials: "JG",
    time: "Today, 4:30 PM",
    agency: "Viral Nation",
  },
  {
    id: "3",
    name: "Nick Cooke",
    initials: "NC",
    time: "Tomorrow, 10:00 AM",
    agency: "The Goat Agency",
  },
];

export const TOTAL_FOLLOW_UPS_COUNT = 86;

export const TYPE_ICONS = {
  WhatsApp: MessageCircle,
  Email: Mail,
  "Phone Call": Phone,
} as const;
