import {
  BarChart3,
  BookOpen,
  Boxes,
  Cloud,
  FileSpreadsheet,
  FileText,
  FileType2,
  FolderPlus,
  Gauge,
  HardDrive,
  Link2,
  MessageSquare,
  Type,
  Upload,
  Users,
} from "lucide-react";
import type {
  ActivityItem,
  DocType,
  KbDocument,
  KbMetric,
  OverviewSegment,
  QuickAction,
  TagCount,
} from "./types";

export const KB_METRICS: KbMetric[] = [
  {
    id: "documents",
    label: "Total Documents",
    value: 128,
    trend: 16,
    trendDirection: "up",
    trendLabel: "vs May 13 – May 19",
    icon: BookOpen,
    iconBg: "#ede9fe",
    iconColor: "#7c3aed",
  },
  {
    id: "size",
    label: "Total Size",
    value: 2.43,
    trend: 12,
    trendDirection: "up",
    trendLabel: "vs May 13 – May 19",
    icon: HardDrive,
    iconBg: "#dcfce7",
    iconColor: "#22c55e",
    formatValue: (value) => `${value.toFixed(2)} GB`,
  },
  {
    id: "chunks",
    label: "Chunks",
    value: 24680,
    trend: 18,
    trendDirection: "up",
    trendLabel: "vs May 13 – May 19",
    icon: Boxes,
    iconBg: "#ffedd5",
    iconColor: "#f97316",
  },
  {
    id: "queries",
    label: "Queries This Week",
    value: 1248,
    trend: 24,
    trendDirection: "up",
    trendLabel: "vs May 13 – May 19",
    icon: MessageSquare,
    iconBg: "#dbeafe",
    iconColor: "#3b82f6",
  },
  {
    id: "accuracy",
    label: "Accuracy Score",
    value: 93,
    trend: 5,
    trendDirection: "up",
    trendLabel: "vs May 13 – May 19",
    icon: Gauge,
    iconBg: "#f3e8ff",
    iconColor: "#a855f7",
    formatValue: (value) => `${Math.round(value)}%`,
    valueBadge: "Excellent",
  },
];

export const TYPE_ICONS: Record<DocType, typeof FileText> = {
  PDF: FileType2,
  DOCX: FileText,
  PPTX: FileType2,
  TXT: Type,
  XLSX: FileSpreadsheet,
  Other: FileText,
};

export const TYPE_COLORS: Record<DocType, string> = {
  PDF: "#ef4444",
  DOCX: "#3b82f6",
  PPTX: "#f97316",
  TXT: "#6b7280",
  XLSX: "#22c55e",
  Other: "#a855f7",
};

const AGENTS = {
  ava: { id: "ava", initials: "AV", color: "#7c3aed" },
  leo: { id: "leo", initials: "LE", color: "#ec4899" },
  mia: { id: "mia", initials: "MI", color: "#3b82f6" },
  zoe: { id: "zoe", initials: "ZO", color: "#22c55e" },
};

export const KB_DOCUMENTS: KbDocument[] = [
  {
    id: "1",
    name: "Company Overview.pdf",
    tags: ["Company", "Overview"],
    type: "PDF",
    size: "2.4 MB",
    uploadedByName: "You",
    uploadedByInitials: "BC",
    uploadedByColor: "#7c3aed",
    uploadedByYou: true,
    uploadedDate: "May 20, 2025",
    agents: [AGENTS.ava, AGENTS.leo],
    extraAgents: 2,
    chunks: 2156,
    status: "Indexed",
    lastUpdatedDate: "May 20, 2025",
    lastUpdatedTime: "09:15 AM",
    source: "Upload",
  },
  {
    id: "2",
    name: "Real Estate Process.docx",
    tags: ["Process", "Guidelines"],
    type: "DOCX",
    size: "1.8 MB",
    uploadedByName: "You",
    uploadedByInitials: "BC",
    uploadedByColor: "#7c3aed",
    uploadedByYou: true,
    uploadedDate: "May 19, 2025",
    agents: [AGENTS.ava],
    extraAgents: 1,
    chunks: 1842,
    status: "Indexed",
    lastUpdatedDate: "May 19, 2025",
    lastUpdatedTime: "04:30 PM",
    source: "Upload",
  },
  {
    id: "3",
    name: "Pricing & Payment Terms.pdf",
    tags: ["Pricing", "Finance"],
    type: "PDF",
    size: "1.2 MB",
    uploadedByName: "Sarah Johnson",
    uploadedByInitials: "SJ",
    uploadedByColor: "#3b82f6",
    uploadedByYou: false,
    uploadedDate: "May 18, 2025",
    agents: [AGENTS.ava, AGENTS.leo, AGENTS.mia],
    extraAgents: 3,
    chunks: 1256,
    status: "Indexed",
    lastUpdatedDate: "May 18, 2025",
    lastUpdatedTime: "11:20 AM",
    source: "Upload",
  },
  {
    id: "4",
    name: "Product Presentation.pptx",
    tags: ["Presentation"],
    type: "PPTX",
    size: "5.6 MB",
    uploadedByName: "You",
    uploadedByInitials: "BC",
    uploadedByColor: "#7c3aed",
    uploadedByYou: true,
    uploadedDate: "May 17, 2025",
    agents: [AGENTS.mia, AGENTS.zoe],
    chunks: 3654,
    status: "Indexed",
    lastUpdatedDate: "May 17, 2025",
    lastUpdatedTime: "02:10 PM",
    source: "Upload",
  },
  {
    id: "5",
    name: "FAQ Document.pdf",
    tags: ["FAQ", "Support"],
    type: "PDF",
    size: "1.5 MB",
    uploadedByName: "Michael Brown",
    uploadedByInitials: "MB",
    uploadedByColor: "#6366f1",
    uploadedByYou: false,
    uploadedDate: "May 16, 2025",
    agents: [AGENTS.ava, AGENTS.leo, AGENTS.mia],
    chunks: 1125,
    status: "Indexed",
    lastUpdatedDate: "May 16, 2025",
    lastUpdatedTime: "09:45 AM",
    source: "Upload",
  },
  {
    id: "6",
    name: "Brand Voice & Tone.txt",
    tags: ["Brand"],
    type: "TXT",
    size: "24 KB",
    uploadedByName: "You",
    uploadedByInitials: "BC",
    uploadedByColor: "#7c3aed",
    uploadedByYou: true,
    uploadedDate: "May 15, 2025",
    agents: [AGENTS.ava],
    chunks: 842,
    status: "Indexed",
    lastUpdatedDate: "May 15, 2025",
    lastUpdatedTime: "05:30 PM",
    source: "Text",
  },
  {
    id: "7",
    name: "Legal Terms & Conditions.pdf",
    tags: ["Legal", "Policies"],
    type: "PDF",
    size: "980 KB",
    uploadedByName: "Emma Watson",
    uploadedByInitials: "EW",
    uploadedByColor: "#ec4899",
    uploadedByYou: false,
    uploadedDate: "May 14, 2025",
    agents: [AGENTS.ava, AGENTS.mia],
    extraAgents: 2,
    chunks: 1024,
    status: "Processing",
    lastUpdatedDate: "May 14, 2025",
    lastUpdatedTime: "01:20 PM",
    source: "Upload",
  },
  {
    id: "8",
    name: "Neighborhood Guide.docx",
    tags: ["Guide"],
    type: "DOCX",
    size: "2.1 MB",
    uploadedByName: "You",
    uploadedByInitials: "BC",
    uploadedByColor: "#7c3aed",
    uploadedByYou: true,
    uploadedDate: "May 13, 2025",
    agents: [AGENTS.zoe],
    chunks: 1934,
    status: "Indexed",
    lastUpdatedDate: "May 13, 2025",
    lastUpdatedTime: "10:00 AM",
    source: "Upload",
  },
];

export const KB_OVERVIEW_SEGMENTS: OverviewSegment[] = [
  { id: "pdf", label: "PDF", value: 56, color: "#ef4444" },
  { id: "docx", label: "DOCX", value: 36, color: "#3b82f6" },
  { id: "pptx", label: "PPTX", value: 12, color: "#f97316" },
  { id: "txt", label: "TXT", value: 8, color: "#a855f7" },
  { id: "other", label: "Other", value: 16, color: "#9ca3af" },
];

export const KB_TOP_TAGS: TagCount[] = [
  { id: "company", label: "Company", count: 24 },
  { id: "process", label: "Process", count: 18 },
  { id: "pricing", label: "Pricing", count: 16 },
  { id: "faq", label: "FAQ", count: 12 },
  { id: "guidelines", label: "Guidelines", count: 10 },
];

export const KB_EXTRA_TAG_COUNT = 8;

export const KB_RECENT_ACTIVITY: ActivityItem[] = [
  {
    id: "1",
    title: "Company Overview.pdf was indexed",
    timestamp: "2 min ago",
    type: "PDF",
  },
  {
    id: "2",
    title: "Pricing & Payment Terms.pdf was updated",
    timestamp: "26 min ago",
    type: "PDF",
  },
  {
    id: "3",
    title: "New document uploaded: Brand Voice & Tone.txt",
    timestamp: "1 hour ago",
    type: "TXT",
  },
  {
    id: "4",
    title: "FAQ Document.pdf was indexed",
    timestamp: "2 hours ago",
    type: "PDF",
  },
  {
    id: "5",
    title: "Real Estate Process.docx was updated",
    timestamp: "3 hours ago",
    type: "DOCX",
  },
];

export const KB_QUICK_ACTIONS: QuickAction[] = [
  { id: "upload", label: "Upload Document", icon: Upload },
  { id: "folder", label: "Create Folder", icon: FolderPlus },
  { id: "url", label: "Add from URL", icon: Link2 },
  { id: "text", label: "Text Document", icon: FileText },
  { id: "drive", label: "Connect Drive", icon: Cloud },
  { id: "agents", label: "View All Agents", icon: Users },
];

export const FILTER_DROPDOWNS = [
  "All Types",
  "All Agents",
  "All Sources",
  "All Tags",
] as const;

export const OVERVIEW_ICONS = { BarChart3 };
