import {
  Eye,
  Handshake,
  Reply,
  Send,
} from "lucide-react";
import type {
  PitchMetric,
  PitchPerformanceSegment,
  PitchRecord,
  ReplyRatePoint,
  TopPerformingPitch,
} from "./types";

export const PITCH_METRICS: PitchMetric[] = [
  {
    id: "total",
    label: "Total Pitches",
    value: 218,
    trend: 18,
    trendDirection: "up",
    trendLabel: "vs last month",
    icon: Send,
    iconBg: "#ede9fe",
    iconColor: "#7c3aed",
  },
  {
    id: "sent",
    label: "Sent",
    value: 142,
    trend: 12,
    trendDirection: "up",
    trendLabel: "vs last month",
    icon: Send,
    iconBg: "#dbeafe",
    iconColor: "#3b82f6",
  },
  {
    id: "viewed",
    label: "Viewed",
    value: 86,
    trend: 8,
    trendDirection: "up",
    trendLabel: "vs last month",
    icon: Eye,
    iconBg: "#ffedd5",
    iconColor: "#f97316",
  },
  {
    id: "replied",
    label: "Replied",
    value: 34,
    trend: 15,
    trendDirection: "up",
    trendLabel: "vs last month",
    icon: Reply,
    iconBg: "#dcfce7",
    iconColor: "#22c55e",
  },
  {
    id: "converted",
    label: "Converted",
    value: 18,
    trend: 6,
    trendDirection: "up",
    trendLabel: "vs last month",
    icon: Handshake,
    iconBg: "#ede9fe",
    iconColor: "#7c3aed",
  },
];

export const PITCH_RECORDS: PitchRecord[] = [
  {
    id: "1",
    title: "WhatsApp Negotiation Agent Pitch",
    agentType: "Negotiation Agent",
    agency: "Ubiquitous",
    recipientName: "Matt Ziel",
    recipientEmail: "matt@ubiquitous.io",
    recipientInitials: "MZ",
    status: "Viewed",
    sentOn: "Jun 28, 2025",
    lastActivity: "2h ago",
    replyRate: 72,
  },
  {
    id: "2",
    title: "Creator Rate Automation Proposal",
    agentType: "Real Estate Agent",
    agency: "Viral Nation",
    recipientName: "Joe Gagliese",
    recipientEmail: "joe@viralnation.com",
    recipientInitials: "JG",
    status: "Replied",
    sentOn: "Jun 27, 2025",
    lastActivity: "5h ago",
    replyRate: 85,
  },
  {
    id: "3",
    title: "Influencer Outreach Platform",
    agentType: "Lead Generation Agent",
    agency: "The Goat Agency",
    recipientName: "Nick Cooke",
    recipientEmail: "hello@thegoatagency.com",
    recipientInitials: "NC",
    status: "Sent",
    sentOn: "Jun 26, 2025",
    lastActivity: "1d ago",
    replyRate: 45,
  },
  {
    id: "4",
    title: "UGC Campaign Automation",
    agentType: "UGC Agent",
    agency: "House of Marketers",
    recipientName: "Inigo Rivero",
    recipientEmail: "inigo@houseofmarketers.com",
    recipientInitials: "IR",
    status: "Converted",
    sentOn: "Jun 24, 2025",
    lastActivity: "2d ago",
    replyRate: 92,
  },
  {
    id: "5",
    title: "Booking Agent for Influencer Deals",
    agentType: "Booking Agent",
    agency: "Billion Dollar Boy",
    recipientName: "Edward East",
    recipientEmail: "hello@billiondollarboy.com",
    recipientInitials: "EE",
    status: "Draft",
    sentOn: "—",
    lastActivity: "3d ago",
    replyRate: 0,
  },
  {
    id: "6",
    title: "Multi-Channel Pitch Sequence",
    agentType: "Custom Agent",
    agency: "Influencer",
    recipientName: "Ben Jeffries",
    recipientEmail: "ben@influencer.com",
    recipientInitials: "BJ",
    status: "Viewed",
    sentOn: "Jun 22, 2025",
    lastActivity: "4d ago",
    replyRate: 58,
  },
];

export const PITCH_PERFORMANCE: PitchPerformanceSegment[] = [
  { label: "Sent", value: 35, color: "#3b82f6" },
  { label: "Viewed", value: 28, color: "#f97316" },
  { label: "Replied", value: 18, color: "#22c55e" },
  { label: "Converted", value: 12, color: "#7c3aed" },
  { label: "Drafts", value: 7, color: "#9ca3af" },
];

export const REPLY_RATE_DATA: ReplyRatePoint[] = [
  { label: "Jun 1", value: 12 },
  { label: "Jun 5", value: 18 },
  { label: "Jun 10", value: 22 },
  { label: "Jun 15", value: 28 },
  { label: "Jun 20", value: 32 },
  { label: "Jun 25", value: 38 },
  { label: "Jun 30", value: 42 },
];

export const TOP_PERFORMING_PITCHES: TopPerformingPitch[] = [
  { id: "1", name: "UGC Campaign Automation", replyRate: 92 },
  { id: "2", name: "Creator Rate Automation", replyRate: 85 },
  { id: "3", name: "WhatsApp Negotiation Agent", replyRate: 72 },
  { id: "4", name: "Multi-Channel Pitch Sequence", replyRate: 58 },
  { id: "5", name: "Influencer Outreach Platform", replyRate: 45 },
];

export const TOTAL_PITCHES_COUNT = 218;
