import {
  Briefcase,
  FileText,
  Mail,
  MessageCircle,
  MessageSquare,
  Send,
} from "lucide-react";
import type { ConversationThread } from "./types";

export const JOHN_SMITH_MESSAGES = [
  {
    id: "m1",
    direction: "incoming" as const,
    content:
      "Hi, I'm interested in your WhatsApp automation product for our agency. We manage 50+ creators and need a better way to handle outreach.",
    timestamp: "10:12 AM",
    dateLabel: "Today",
  },
  {
    id: "m2",
    direction: "incoming" as const,
    content:
      "Can you send me more details about pricing and features? We're currently using a manual process and it's taking too much time.",
    timestamp: "10:15 AM",
  },
  {
    id: "m3",
    direction: "outgoing" as const,
    content:
      "Hi John, thanks for reaching out! Our WhatsApp Agent automates creator outreach, follow-ups, and reply handling — saving agencies 15+ hours per week.",
    timestamp: "10:25 AM",
    read: true,
  },
  {
    id: "m4",
    direction: "outgoing" as const,
    content:
      "I'd love to schedule a quick call to walk you through the platform and discuss how it fits your workflow. Would tomorrow at 2 PM work?",
    timestamp: "10:26 AM",
    read: true,
  },
  {
    id: "m5",
    direction: "incoming" as const,
    content: "That sounds great. How about tomorrow at 2 PM?",
    timestamp: "10:30 AM",
  },
];

export const CONVERSATION_THREADS: ConversationThread[] = [
  {
    id: "1",
    preview: {
      id: "1",
      contactName: "John Smith",
      initials: "JS",
      avatarColor: "#7c3aed",
      preview:
        "That sounds great. How about tomorrow at 2 PM?",
      timestamp: "10:30 AM",
      channel: "WhatsApp",
      unreadCount: 2,
    },
    contact: {
      name: "John Smith",
      initials: "JS",
      avatarColor: "#7c3aed",
      status: "Active now",
      phone: "+1 (555) 234-5678",
      email: "john.smith@luxuryprops.com",
      location: "Miami, FL",
      company: "Luxury Properties Inc.",
      channel: "WhatsApp",
    },
    messages: JOHN_SMITH_MESSAGES,
    deals: [
      {
        id: "d1",
        title: "Luxury Property Campaign",
        status: "In Discussion",
        value: "$25,000",
        stage: "Proposal Sent",
        updated: "Jun 15, 2025",
      },
    ],
    notes: [
      {
        id: "n1",
        content:
          "Interested in WhatsApp automation for creator outreach. Budget approved for Q3.",
        author: "Sajam J.",
        date: "Jun 14, 2025",
      },
    ],
    activities: [
      {
        id: "a1",
        title: "Conversation started",
        timestamp: "Jun 12, 2025 · 9:45 AM",
        icon: MessageSquare,
        iconBg: "#dcfce7",
        iconColor: "#22c55e",
      },
      {
        id: "a2",
        title: "Deal created",
        timestamp: "Jun 13, 2025 · 2:30 PM",
        icon: Briefcase,
        iconBg: "#ede9fe",
        iconColor: "#7c3aed",
      },
      {
        id: "a3",
        title: "Proposal sent",
        timestamp: "Jun 15, 2025 · 11:00 AM",
        icon: Send,
        iconBg: "#dbeafe",
        iconColor: "#3b82f6",
      },
    ],
  },
  {
    id: "2",
    preview: {
      id: "2",
      contactName: "Sarah Chen",
      initials: "SC",
      avatarColor: "#3b82f6",
      preview: "Thanks for the demo yesterday. Our team loved it!",
      timestamp: "Yesterday",
      channel: "Email",
      unreadCount: 1,
    },
    contact: {
      name: "Sarah Chen",
      initials: "SC",
      avatarColor: "#3b82f6",
      status: "Offline",
      phone: "+1 (555) 876-5432",
      email: "sarah@viralnation.com",
      location: "Los Angeles, CA",
      company: "Viral Nation",
      channel: "Email",
    },
    messages: [
      {
        id: "m1",
        direction: "incoming",
        content: "Thanks for the demo yesterday. Our team loved it!",
        timestamp: "4:15 PM",
        dateLabel: "Yesterday",
      },
    ],
    deals: [],
    notes: [],
    activities: [],
  },
  {
    id: "3",
    preview: {
      id: "3",
      contactName: "Matt Ziel",
      initials: "MZ",
      avatarColor: "#f97316",
      preview: "Can we schedule a follow-up call next week?",
      timestamp: "Jun 1",
      channel: "WhatsApp",
    },
    contact: {
      name: "Matt Ziel",
      initials: "MZ",
      avatarColor: "#f97316",
      status: "Offline",
      phone: "+1 (555) 111-2233",
      email: "matt@ubiquitous.com",
      location: "New York, NY",
      company: "Ubiquitous",
      channel: "WhatsApp",
    },
    messages: [
      {
        id: "m1",
        direction: "incoming",
        content: "Can we schedule a follow-up call next week?",
        timestamp: "11:00 AM",
        dateLabel: "Jun 1",
      },
    ],
    deals: [],
    notes: [],
    activities: [],
  },
  {
    id: "4",
    preview: {
      id: "4",
      contactName: "Joe Gagliese",
      initials: "JG",
      avatarColor: "#22c55e",
      preview: "We're ready to move forward with the pilot.",
      timestamp: "May 28",
      channel: "Email",
      isMention: true,
    },
    contact: {
      name: "Joe Gagliese",
      initials: "JG",
      avatarColor: "#22c55e",
      status: "Offline",
      phone: "+1 (555) 444-5566",
      email: "joe@viralnation.com",
      location: "Toronto, ON",
      company: "Viral Nation",
      channel: "Email",
    },
    messages: [
      {
        id: "m1",
        direction: "incoming",
        content: "We're ready to move forward with the pilot.",
        timestamp: "3:00 PM",
        dateLabel: "May 28",
      },
    ],
    deals: [],
    notes: [],
    activities: [],
  },
  {
    id: "5",
    preview: {
      id: "5",
      contactName: "Nick Cooke",
      initials: "NC",
      avatarColor: "#ec4899",
      preview: "Sent over the contract for review.",
      timestamp: "May 25",
      channel: "WhatsApp",
    },
    contact: {
      name: "Nick Cooke",
      initials: "NC",
      avatarColor: "#ec4899",
      status: "Offline",
      phone: "+44 20 7946 0958",
      email: "nick@goatagency.com",
      location: "London, UK",
      company: "The Goat Agency",
      channel: "WhatsApp",
    },
    messages: [
      {
        id: "m1",
        direction: "outgoing",
        content: "Sent over the contract for review.",
        timestamp: "2:00 PM",
        dateLabel: "May 25",
        read: true,
      },
    ],
    deals: [],
    notes: [],
    activities: [],
  },
  {
    id: "6",
    preview: {
      id: "6",
      contactName: "Inigo Rivero",
      initials: "IR",
      avatarColor: "#14b8a6",
      preview: "Let me check with the team and get back to you.",
      timestamp: "May 22",
      channel: "Email",
    },
    contact: {
      name: "Inigo Rivero",
      initials: "IR",
      avatarColor: "#14b8a6",
      status: "Offline",
      phone: "+34 91 123 4567",
      email: "inigo@houseofmarketers.com",
      location: "Madrid, Spain",
      company: "House of Marketers",
      channel: "Email",
    },
    messages: [
      {
        id: "m1",
        direction: "incoming",
        content: "Let me check with the team and get back to you.",
        timestamp: "9:30 AM",
        dateLabel: "May 22",
      },
    ],
    deals: [],
    notes: [],
    activities: [],
  },
  {
    id: "7",
    preview: {
      id: "7",
      contactName: "Ben Jeffries",
      initials: "BJ",
      avatarColor: "#6366f1",
      preview: "Great pitch deck. When can we do a live demo?",
      timestamp: "May 18",
      channel: "WhatsApp",
      unreadCount: 3,
    },
    contact: {
      name: "Ben Jeffries",
      initials: "BJ",
      avatarColor: "#6366f1",
      status: "Offline",
      phone: "+44 20 1234 5678",
      email: "ben@influencer.com",
      location: "London, UK",
      company: "Influencer",
      channel: "WhatsApp",
    },
    messages: [
      {
        id: "m1",
        direction: "incoming",
        content: "Great pitch deck. When can we do a live demo?",
        timestamp: "1:45 PM",
        dateLabel: "May 18",
      },
    ],
    deals: [],
    notes: [],
    activities: [],
  },
  {
    id: "8",
    preview: {
      id: "8",
      contactName: "Edward East",
      initials: "EE",
      avatarColor: "#a855f7",
      preview: "Archived — campaign completed successfully.",
      timestamp: "Apr 30",
      channel: "Email",
      isArchived: true,
    },
    contact: {
      name: "Edward East",
      initials: "EE",
      avatarColor: "#a855f7",
      status: "Offline",
      phone: "+44 20 9876 5432",
      email: "edward@bdb.com",
      location: "London, UK",
      company: "Billion Dollar Boy",
      channel: "Email",
    },
    messages: [
      {
        id: "m1",
        direction: "incoming",
        content: "Campaign completed successfully. Thanks for everything!",
        timestamp: "5:00 PM",
        dateLabel: "Apr 30",
      },
    ],
    deals: [],
    notes: [],
    activities: [],
  },
];

export const CHANNEL_ICONS = {
  WhatsApp: MessageCircle,
  Email: Mail,
  SMS: MessageSquare,
} as const;

export const CHANNEL_COLORS: Record<string, string> = {
  WhatsApp: "#22c55e",
  Email: "#3b82f6",
  SMS: "#f97316",
};
