import {
  Building2,
  CheckSquare,
  MessageCircle,
  Send,
  Timer,
} from "lucide-react";
import type {
  ActivityItem,
  ChartDataPoint,
  DashboardMetric,
  RecentConversation,
  TopAgency,
} from "./types";

export const DASHBOARD_METRICS: DashboardMetric[] = [
  {
    id: "agencies",
    label: "Total Agencies",
    value: 52,
    trend: 12,
    trendDirection: "up",
    trendLabel: "vs last month",
    icon: Building2,
    iconBg: "#ede9fe",
    iconColor: "#7c3aed",
  },
  {
    id: "pitches",
    label: "Total Pitches",
    value: 218,
    trend: 18,
    trendDirection: "up",
    trendLabel: "vs last month",
    icon: Send,
    iconBg: "#dbeafe",
    iconColor: "#3b82f6",
  },
  {
    id: "conversations",
    label: "Total Conversations",
    value: 1248,
    trend: 20,
    trendDirection: "up",
    trendLabel: "vs last month",
    icon: MessageCircle,
    iconBg: "#ffedd5",
    iconColor: "#f97316",
  },
  {
    id: "follow-ups",
    label: "Follow Ups",
    value: 86,
    trend: 5,
    trendDirection: "down",
    trendLabel: "vs last month",
    icon: Timer,
    iconBg: "#fce7f3",
    iconColor: "#ec4899",
  },
  {
    id: "tasks",
    label: "Tasks Pending",
    value: 34,
    trend: 8,
    trendDirection: "down",
    trendLabel: "vs last month",
    icon: CheckSquare,
    iconBg: "#dcfce7",
    iconColor: "#22c55e",
  },
];

export const CONVERSATION_CHART_DATA: ChartDataPoint[] = [
  { label: "Jan", value: 420 },
  { label: "Feb", value: 510 },
  { label: "Mar", value: 480 },
  { label: "Apr", value: 620 },
  { label: "May", value: 780 },
  { label: "Jun", value: 920 },
  { label: "Jul", value: 1050 },
];

export const RECENT_CONVERSATIONS: RecentConversation[] = [
  {
    id: "1",
    name: "Matt Ziel",
    initials: "MZ",
    agency: "Ubiquitous",
    message: "Interested in scheduling a demo for the negotiation agent...",
    timeAgo: "2m ago",
    status: "New",
  },
  {
    id: "2",
    name: "Joe Gagliese",
    initials: "JG",
    agency: "Viral Nation",
    message: "Thanks for the pitch deck. Can we discuss pricing next week?",
    timeAgo: "15m ago",
    status: "Replied",
  },
  {
    id: "3",
    name: "Nick Cooke",
    initials: "NC",
    agency: "The Goat Agency",
    message: "We've reviewed your proposal and would like to move forward.",
    timeAgo: "1h ago",
    status: "Closed",
  },
  {
    id: "4",
    name: "Ben Jeffries",
    initials: "BJ",
    agency: "Influencer",
    message: "Following up on our WhatsApp conversation from yesterday.",
    timeAgo: "3h ago",
    status: "Replied",
  },
];

export const TOP_AGENCIES: TopAgency[] = [
  {
    id: "1",
    name: "Ubiquitous",
    initials: "U",
    color: "#7c3aed",
    conversations: 142,
    replyRate: 78,
    deals: 12,
  },
  {
    id: "2",
    name: "Viral Nation",
    initials: "VN",
    color: "#3b82f6",
    conversations: 128,
    replyRate: 72,
    deals: 9,
  },
  {
    id: "3",
    name: "The Goat Agency",
    initials: "TG",
    color: "#22c55e",
    conversations: 96,
    replyRate: 65,
    deals: 7,
  },
  {
    id: "4",
    name: "House of Marketers",
    initials: "HM",
    color: "#f97316",
    conversations: 84,
    replyRate: 58,
    deals: 5,
  },
];

export const ACTIVITY_FEED: ActivityItem[] = [
  {
    id: "1",
    description: "New agency Acme Real Estate was created",
    timeAgo: "5m ago",
    icon: Building2,
    iconBg: "#ede9fe",
    iconColor: "#7c3aed",
  },
  {
    id: "2",
    description: "Pitch sent to Viral Nation via WhatsApp",
    timeAgo: "22m ago",
    icon: Send,
    iconBg: "#dbeafe",
    iconColor: "#3b82f6",
  },
  {
    id: "3",
    description: "New conversation started with Matt Ziel",
    timeAgo: "1h ago",
    icon: MessageCircle,
    iconBg: "#ffedd5",
    iconColor: "#f97316",
  },
  {
    id: "4",
    description: "Follow-up reminder set for The Goat Agency",
    timeAgo: "2h ago",
    icon: Timer,
    iconBg: "#fce7f3",
    iconColor: "#ec4899",
  },
  {
    id: "5",
    description: "Task completed: Review Q2 outreach report",
    timeAgo: "4h ago",
    icon: CheckSquare,
    iconBg: "#dcfce7",
    iconColor: "#22c55e",
  },
];
