import {
  CalendarCheck,
  CalendarX,
  CheckCircle2,
  DollarSign,
  Globe,
  Mail,
  MapPin,
  MessageCircle,
  Phone,
  Share2,
  Sparkles,
  Video,
} from "lucide-react";
import type { BookingActivity, BookingMetric, BookingRecord } from "./types";

export const BOOKING_METRICS: BookingMetric[] = [
  {
    id: "total",
    label: "Total Bookings",
    value: 87,
    trend: 21,
    trendDirection: "up",
    trendLabel: "vs May 13 – May 19",
    icon: CalendarCheck,
    iconBg: "#ede9fe",
    iconColor: "#7c3aed",
  },
  {
    id: "upcoming",
    label: "Upcoming",
    value: 43,
    trend: 18,
    trendDirection: "up",
    trendLabel: "vs May 13 – May 19",
    icon: CalendarCheck,
    iconBg: "#dcfce7",
    iconColor: "#22c55e",
  },
  {
    id: "completed",
    label: "Completed",
    value: 32,
    trend: 16,
    trendDirection: "up",
    trendLabel: "vs May 13 – May 19",
    icon: CheckCircle2,
    iconBg: "#ffedd5",
    iconColor: "#f97316",
  },
  {
    id: "cancelled",
    label: "Cancelled",
    value: 7,
    trend: 12,
    trendDirection: "down",
    trendLabel: "vs May 13 – May 19",
    icon: CalendarX,
    iconBg: "#fce7f3",
    iconColor: "#ec4899",
  },
  {
    id: "revenue",
    label: "Revenue From Bookings",
    value: 24780,
    trend: 32,
    trendDirection: "up",
    trendLabel: "vs May 13 – May 19",
    icon: DollarSign,
    iconBg: "#dbeafe",
    iconColor: "#3b82f6",
    formatValue: (value) => `$${value.toLocaleString()}`,
  },
];

const JOHN_SMITH_ACTIVITIES: BookingActivity[] = [
  {
    id: "1",
    title: "Booking confirmed via WhatsApp",
    timestamp: "May 20, 2025 · 2:15 PM",
  },
  {
    id: "2",
    title: "Reminder sent to client",
    timestamp: "May 21, 2025 · 9:00 AM",
  },
  {
    id: "3",
    title: "Google Meet link shared",
    timestamp: "May 21, 2025 · 9:01 AM",
  },
];

export const BOOKING_RECORDS: BookingRecord[] = [
  {
    id: "1",
    name: "John Smith",
    email: "john.smith@email.com",
    phone: "+1 (555) 234-5678",
    purpose: "Property Consultation",
    purposeDescription:
      "Interested in a 2BHK apartment in downtown Miami. Wants to discuss floor plans, pricing, and financing options during the consultation.",
    label: "New",
    initials: "JS",
    avatarColor: "#7c3aed",
    location: "New York, USA",
    source: "WhatsApp",
    agentName: "Real Estate Agent",
    agentRole: "Scheduling",
    meetingType: "Video Call",
    date: "May 22, 2025",
    time: "10:00 AM",
    endTime: "10:45 AM",
    duration: "45 min",
    calendarMonth: 4,
    calendarYear: 2025,
    calendarDay: 22,
    status: "Upcoming",
    bookedBy: "AI Agent",
    bookedOn: "May 20, 2025 · 2:15 PM",
    timeZone: "EST (UTC-5)",
    meetingLink: "https://meet.google.com/abc-defg-hij",
    meetingPlatform: "Google Meet",
    activities: JOHN_SMITH_ACTIVITIES,
  },
  {
    id: "2",
    name: "Sarah Mitchell",
    email: "sarah.m@email.com",
    phone: "+1 (555) 876-5432",
    purpose: "Product Demo",
    purposeDescription:
      "Enterprise plan demo for a team of 15 sales reps. Focus on AI agent customization and CRM integration.",
    label: "Confirmed",
    initials: "SM",
    avatarColor: "#3b82f6",
    location: "Austin, TX",
    source: "Website",
    agentName: "Booking Assistant",
    agentRole: "Scheduling",
    meetingType: "Video Call",
    date: "May 23, 2025",
    time: "2:30 PM",
    calendarMonth: 4,
    calendarYear: 2025,
    calendarDay: 23,
    status: "Upcoming",
    bookedBy: "Sarah Mitchell",
    bookedOn: "May 19, 2025 · 11:00 AM",
    timeZone: "CST (UTC-6)",
    meetingLink: "https://meet.google.com/xyz-uvwx-rst",
    meetingPlatform: "Google Meet",
    activities: [],
  },
  {
    id: "3",
    name: "James Cooper",
    email: "james.cooper@email.com",
    phone: "+1 (555) 111-2233",
    purpose: "Site Visit",
    purposeDescription:
      "On-site tour of luxury penthouse units. Client is a qualified buyer with pre-approved financing.",
    label: "Confirmed",
    initials: "JC",
    avatarColor: "#22c55e",
    location: "Denver, CO",
    source: "Instagram",
    agentName: "Real Estate Agent",
    agentRole: "Scheduling",
    meetingType: "On-Site Visit",
    date: "May 24, 2025",
    time: "11:00 AM",
    calendarMonth: 4,
    calendarYear: 2025,
    calendarDay: 24,
    status: "Upcoming",
    bookedBy: "James Cooper",
    bookedOn: "May 18, 2025 · 4:30 PM",
    timeZone: "MST (UTC-7)",
    activities: [],
  },
  {
    id: "4",
    name: "Emily Rodriguez",
    email: "emily.r@email.com",
    phone: "+1 (555) 444-5566",
    purpose: "Brand Collaboration Call",
    purposeDescription:
      "UGC creator discussing campaign deliverables and content guidelines for summer launch.",
    initials: "ER",
    avatarColor: "#ec4899",
    location: "Los Angeles, CA",
    source: "Instagram",
    agentName: "UGC Campaign Agent",
    agentRole: "Content Outreach",
    meetingType: "Video Call",
    date: "May 21, 2025",
    time: "3:00 PM",
    calendarMonth: 4,
    calendarYear: 2025,
    calendarDay: 21,
    status: "Completed",
    bookedBy: "Emily Rodriguez",
    bookedOn: "May 15, 2025 · 10:00 AM",
    timeZone: "PST (UTC-8)",
    meetingLink: "https://meet.google.com/emily-rod",
    meetingPlatform: "Google Meet",
    activities: [
      {
        id: "1",
        title: "Meeting completed successfully",
        timestamp: "May 21, 2025 · 3:45 PM",
      },
    ],
  },
  {
    id: "5",
    name: "David Park",
    email: "david.park@email.com",
    phone: "+1 (555) 777-8899",
    purpose: "Sales Onboarding",
    purposeDescription:
      "Annual Pro plan onboarding session. Walk through dashboard, agent setup, and integrations.",
    label: "Confirmed",
    initials: "DP",
    avatarColor: "#f97316",
    location: "Seattle, WA",
    source: "Facebook",
    agentName: "Lead Qualification Agent",
    agentRole: "Sales",
    meetingType: "Video Call",
    date: "May 19, 2025",
    time: "9:00 AM",
    calendarMonth: 4,
    calendarYear: 2025,
    calendarDay: 19,
    status: "Completed",
    bookedBy: "David Park",
    bookedOn: "May 12, 2025 · 3:00 PM",
    timeZone: "PST (UTC-8)",
    activities: [],
  },
  {
    id: "6",
    name: "Lisa Chen",
    email: "lisa.chen@email.com",
    phone: "+1 (555) 333-4455",
    purpose: "Office Space Tour",
    purposeDescription:
      "Commercial office space viewing. Client needs 2,000 sq ft with parking for 10 vehicles.",
    initials: "LC",
    avatarColor: "#14b8a6",
    location: "San Francisco, CA",
    source: "WhatsApp",
    agentName: "Real Estate Agent",
    agentRole: "Scheduling",
    meetingType: "On-Site Visit",
    date: "May 25, 2025",
    time: "1:00 PM",
    calendarMonth: 4,
    calendarYear: 2025,
    calendarDay: 25,
    status: "Upcoming",
    bookedBy: "Lisa Chen",
    bookedOn: "May 20, 2025 · 9:30 AM",
    timeZone: "PST (UTC-8)",
    activities: [],
  },
  {
    id: "7",
    name: "Michael Brown",
    email: "m.brown@email.com",
    phone: "+1 (555) 222-3344",
    purpose: "Support Follow-up",
    purposeDescription:
      "Follow-up call regarding billing issue. Client requested cancellation of original appointment.",
    initials: "MB",
    avatarColor: "#6366f1",
    location: "Chicago, IL",
    source: "Email",
    agentName: "E-Commerce Support Agent",
    agentRole: "Support",
    meetingType: "Phone Call",
    date: "May 20, 2025",
    time: "4:00 PM",
    calendarMonth: 4,
    calendarYear: 2025,
    calendarDay: 20,
    status: "Cancelled",
    bookedBy: "Michael Brown",
    bookedOn: "May 17, 2025 · 2:00 PM",
    timeZone: "CST (UTC-6)",
    activities: [
      {
        id: "1",
        title: "Booking cancelled by client",
        timestamp: "May 19, 2025 · 5:30 PM",
      },
    ],
  },
  {
    id: "8",
    name: "Anna Wilson",
    email: "anna.w@email.com",
    phone: "+1 (555) 666-7788",
    purpose: "Mortgage Consultation",
    purposeDescription:
      "First-time homebuyer pre-approval discussion. Budget $280K with 10% down payment.",
    label: "New",
    initials: "AW",
    avatarColor: "#a855f7",
    location: "Boston, MA",
    source: "Website",
    agentName: "Real Estate Agent",
    agentRole: "Scheduling",
    meetingType: "Video Call",
    date: "May 26, 2025",
    time: "11:30 AM",
    calendarMonth: 4,
    calendarYear: 2025,
    calendarDay: 26,
    status: "Upcoming",
    bookedBy: "Anna Wilson",
    bookedOn: "May 21, 2025 · 8:45 AM",
    timeZone: "EST (UTC-5)",
    meetingLink: "https://meet.google.com/anna-wilson",
    meetingPlatform: "Google Meet",
    activities: [],
  },
];

export const SOURCE_ICONS = {
  WhatsApp: MessageCircle,
  Instagram: Sparkles,
  Website: Globe,
  Facebook: Share2,
  Email: Mail,
} as const;

export const SOURCE_COLORS: Record<string, string> = {
  WhatsApp: "#22c55e",
  Instagram: "#ec4899",
  Website: "#7c3aed",
  Facebook: "#3b82f6",
  Email: "#6b7280",
};

export const MEETING_TYPE_ICONS = {
  "Video Call": Video,
  "On-Site Visit": MapPin,
  "Phone Call": Phone,
} as const;

export const SORT_OPTIONS = [
  { value: "newest", label: "Newest First" },
  { value: "oldest", label: "Oldest First" },
  { value: "date", label: "Date & Time" },
] as const;
