import {
  Bot,
  CalendarCheck,
  DollarSign,
  Globe,
  Headphones,
  Home,
  MessageCircle,
  MessageSquare,
  ShoppingBag,
  Users,
  Video,
} from "lucide-react";
import type {
  AgentHealthSegment,
  AgentMetric,
  AgentRecord,
  TopPerformingAgentInfo,
} from "./types";

export const AGENT_METRICS: AgentMetric[] = [
  {
    id: "total",
    label: "Total Agents",
    value: 6,
    icon: Bot,
    iconBg: "#ede9fe",
    iconColor: "#7c3aed",
    subtext: "4 Active · 1 Training · 1 Paused",
  },
  {
    id: "leads",
    label: "Total Leads Generated",
    value: 428,
    icon: Users,
    iconBg: "#dcfce7",
    iconColor: "#22c55e",
    trend: 24,
    trendDirection: "up",
    trendLabel: "vs last month",
  },
  {
    id: "conversations",
    label: "Conversations Handled",
    value: 1248,
    icon: MessageSquare,
    iconBg: "#dbeafe",
    iconColor: "#3b82f6",
    trend: 18,
    trendDirection: "up",
    trendLabel: "vs last month",
  },
  {
    id: "bookings",
    label: "Bookings Completed",
    value: 87,
    icon: CalendarCheck,
    iconBg: "#ffedd5",
    iconColor: "#f97316",
    trend: 21,
    trendDirection: "up",
    trendLabel: "vs last month",
  },
  {
    id: "revenue",
    label: "Revenue Influenced",
    value: 24780,
    icon: DollarSign,
    iconBg: "#ede9fe",
    iconColor: "#7c3aed",
    trend: 32,
    trendDirection: "up",
    trendLabel: "vs last month",
    formatValue: (value) =>
      value >= 1000 ? `$${value.toLocaleString()}` : `$${value}`,
  },
];

export const AGENT_RECORDS: AgentRecord[] = [
  {
    id: "1",
    name: "Real Estate Outreach Agent",
    description: "Qualifies property leads and schedules viewings automatically.",
    icon: Home,
    iconBg: "#ede9fe",
    iconColor: "#7c3aed",
    isPrimary: true,
    status: "Active",
    platforms: ["WhatsApp", "Instagram", "Web"],
    leads: { label: "Leads", value: 124, trend: 18, trendDirection: "up" },
    conversations: {
      label: "Conversations",
      value: 386,
      trend: 22,
      trendDirection: "up",
    },
    thirdMetric: {
      label: "Bookings",
      value: 28,
      trend: 15,
      trendDirection: "up",
    },
    aiScore: 93,
    sparkline: [78, 82, 85, 88, 90, 92, 93],
    lastUpdated: "2 hours ago",
  },
  {
    id: "2",
    name: "Booking Assistant",
    description: "Handles scheduling, reminders, and calendar sync for meetings.",
    icon: CalendarCheck,
    iconBg: "#ffedd5",
    iconColor: "#f97316",
    status: "Active",
    platforms: ["WhatsApp", "Email", "Web"],
    leads: { label: "Leads", value: 86, trend: 12, trendDirection: "up" },
    conversations: {
      label: "Conversations",
      value: 248,
      trend: 16,
      trendDirection: "up",
    },
    thirdMetric: {
      label: "Bookings",
      value: 42,
      trend: 24,
      trendDirection: "up",
    },
    aiScore: 91,
    sparkline: [72, 76, 80, 84, 87, 89, 91],
    lastUpdated: "5 hours ago",
  },
  {
    id: "3",
    name: "E-Commerce Support Agent",
    description: "Answers product questions and resolves customer inquiries.",
    icon: ShoppingBag,
    iconBg: "#dbeafe",
    iconColor: "#3b82f6",
    status: "Active",
    platforms: ["WhatsApp", "Instagram", "LinkedIn"],
    leads: { label: "Leads", value: 98, trend: 8, trendDirection: "up" },
    conversations: {
      label: "Conversations",
      value: 312,
      trend: 14,
      trendDirection: "up",
    },
    thirdMetric: {
      label: "Resolved",
      value: 276,
      trend: 11,
      trendDirection: "up",
    },
    aiScore: 89,
    sparkline: [80, 82, 84, 85, 87, 88, 89],
    lastUpdated: "Yesterday",
  },
  {
    id: "4",
    name: "UGC Campaign Agent",
    description: "Outreach to creators for UGC content and brand collaborations.",
    icon: Video,
    iconBg: "#fce7f3",
    iconColor: "#ec4899",
    status: "Training",
    platforms: ["Instagram", "Email"],
    leads: { label: "Leads", value: 42, trend: 5, trendDirection: "up" },
    conversations: {
      label: "Conversations",
      value: 96,
      trend: 3,
      trendDirection: "up",
    },
    thirdMetric: {
      label: "Converted",
      value: 18,
      trend: 2,
      trendDirection: "up",
    },
    aiScore: 76,
    sparkline: [60, 64, 68, 70, 72, 74, 76],
    lastUpdated: "2 days ago",
  },
  {
    id: "5",
    name: "Lead Qualification Agent",
    description: "Scores inbound leads and routes hot prospects to your team.",
    icon: Users,
    iconBg: "#dcfce7",
    iconColor: "#22c55e",
    status: "Active",
    platforms: ["WhatsApp", "LinkedIn", "Web"],
    leads: { label: "Leads", value: 56, trend: 10, trendDirection: "up" },
    conversations: {
      label: "Conversations",
      value: 142,
      trend: 8,
      trendDirection: "up",
    },
    thirdMetric: {
      label: "Qualified",
      value: 38,
      trend: 6,
      trendDirection: "up",
    },
    aiScore: 87,
    sparkline: [74, 76, 78, 80, 83, 85, 87],
    lastUpdated: "3 days ago",
  },
  {
    id: "6",
    name: "Customer Support Agent",
    description: "24/7 support for FAQs, order status, and issue resolution.",
    icon: Headphones,
    iconBg: "#f3f4f6",
    iconColor: "#6b7280",
    status: "Paused",
    platforms: ["Web", "Email"],
    leads: { label: "Leads", value: 22, trend: 0, trendDirection: "down" },
    conversations: {
      label: "Conversations",
      value: 64,
      trend: 2,
      trendDirection: "down",
    },
    thirdMetric: {
      label: "Resolved",
      value: 58,
      trend: 1,
      trendDirection: "down",
    },
    aiScore: 72,
    sparkline: [78, 76, 75, 74, 73, 72, 72],
    lastUpdated: "1 week ago",
  },
];

export const AGENT_HEALTH_SEGMENTS: AgentHealthSegment[] = [
  { label: "Active", value: 4, color: "#22c55e" },
  { label: "Training", value: 1, color: "#7c3aed" },
  { label: "Paused", value: 1, color: "#9ca3af" },
  { label: "Offline", value: 0, color: "#e5e7eb" },
];

export const AGENT_HEALTH_TOTAL = AGENT_HEALTH_SEGMENTS.reduce(
  (sum, segment) => sum + segment.value,
  0,
);

export const TOP_PERFORMING_AGENT: TopPerformingAgentInfo = {
  name: "Real Estate Outreach Agent",
  aiScore: 93,
  leadsGenerated: 124,
  revenueInfluenced: "$8,420",
};

export const PLATFORM_COLORS: Record<string, string> = {
  WhatsApp: "#22c55e",
  Instagram: "#ec4899",
  Web: "#3b82f6",
  LinkedIn: "#0ea5e9",
  Email: "#6b7280",
};

export const SORT_OPTIONS = [
  { value: "recently-updated", label: "Recently Updated" },
  { value: "name", label: "Name A–Z" },
  { value: "ai-score", label: "AI Score" },
] as const;
