import {
  DollarSign,
  Home,
  Mail,
  MessageCircle,
  Sparkles,
  Target,
  TrendingUp,
  UserPlus,
  Users,
} from "lucide-react";
import type { LeadActivity, LeadMetric, LeadRecord } from "./types";

export const LEAD_METRICS: LeadMetric[] = [
  {
    id: "total",
    label: "Total Leads",
    value: 428,
    trend: 24,
    trendDirection: "up",
    trendLabel: "vs May 13 – May 19",
    icon: Users,
    iconBg: "#ede9fe",
    iconColor: "#7c3aed",
  },
  {
    id: "new",
    label: "New Leads",
    value: 128,
    trend: 18,
    trendDirection: "up",
    trendLabel: "vs May 13 – May 19",
    icon: UserPlus,
    iconBg: "#dcfce7",
    iconColor: "#22c55e",
  },
  {
    id: "qualified",
    label: "Qualified Leads",
    value: 189,
    trend: 22,
    trendDirection: "up",
    trendLabel: "vs May 13 – May 19",
    icon: Target,
    iconBg: "#ffedd5",
    iconColor: "#f97316",
  },
  {
    id: "converted",
    label: "Converted Leads",
    value: 67,
    trend: 16,
    trendDirection: "up",
    trendLabel: "vs May 13 – May 19",
    icon: TrendingUp,
    iconBg: "#dbeafe",
    iconColor: "#3b82f6",
  },
  {
    id: "revenue",
    label: "Revenue From Leads",
    value: 24780,
    trend: 32,
    trendDirection: "up",
    trendLabel: "vs May 13 – May 19",
    icon: DollarSign,
    iconBg: "#cffafe",
    iconColor: "#06b6d4",
    formatValue: (value) => `$${value.toLocaleString()}`,
  },
];

const JOHN_SMITH_ACTIVITIES: LeadActivity[] = [
  {
    id: "1",
    title: "Lead captured via WhatsApp",
    timestamp: "May 26, 2025 · 9:42 AM",
  },
  {
    id: "2",
    title: "AI agent sent welcome message",
    timestamp: "May 26, 2025 · 9:43 AM",
  },
  {
    id: "3",
    title: "Lead replied with property requirements",
    timestamp: "May 26, 2025 · 10:15 AM",
  },
];

export const LEAD_RECORDS: LeadRecord[] = [
  {
    id: "1",
    name: "John Smith",
    email: "john.smith@email.com",
    phone: "+1 (555) 234-5678",
    tag: "Hot Lead",
    initials: "JS",
    avatarColor: "#7c3aed",
    location: "Miami, FL",
    summary:
      "Interested in purchasing a 2BHK apartment in downtown Miami. Budget range $350K–$450K. Looking to move within 3 months.",
    source: "WhatsApp",
    agentName: "Real Estate Outreach Agent",
    agentRole: "Lead Generation",
    leadScore: 86,
    status: "New",
    lastActivity: "10 min ago",
    capturedOn: "May 26, 2025 · 9:42 AM",
    activities: JOHN_SMITH_ACTIVITIES,
  },
  {
    id: "2",
    name: "Sarah Mitchell",
    email: "sarah.m@email.com",
    phone: "+1 (555) 876-5432",
    initials: "SM",
    avatarColor: "#3b82f6",
    location: "Austin, TX",
    summary:
      "Requested a product demo for enterprise plan. Team of 15 sales reps.",
    source: "Email",
    agentName: "Booking Assistant",
    agentRole: "Scheduling",
    leadScore: 78,
    status: "In Progress",
    lastActivity: "1 hour ago",
    capturedOn: "May 25, 2025 · 2:30 PM",
    assignedTo: "Sajam J.",
    activities: [
      {
        id: "1",
        title: "Demo scheduled for May 28",
        timestamp: "May 25, 2025 · 3:00 PM",
      },
    ],
  },
  {
    id: "3",
    name: "James Cooper",
    email: "james.cooper@email.com",
    phone: "+1 (555) 111-2233",
    tag: "VIP",
    initials: "JC",
    avatarColor: "#22c55e",
    location: "Denver, CO",
    summary: "Qualified buyer for luxury property portfolio. High net worth.",
    source: "Web",
    agentName: "Real Estate Outreach Agent",
    agentRole: "Lead Generation",
    leadScore: 92,
    status: "Qualified",
    lastActivity: "3 hours ago",
    capturedOn: "May 24, 2025 · 11:00 AM",
    activities: [],
  },
  {
    id: "4",
    name: "Emily Rodriguez",
    email: "emily.r@email.com",
    phone: "+1 (555) 444-5566",
    initials: "ER",
    avatarColor: "#ec4899",
    location: "Los Angeles, CA",
    summary: "UGC creator interested in brand collaboration campaign.",
    source: "Instagram",
    agentName: "UGC Campaign Agent",
    agentRole: "Content Outreach",
    leadScore: 64,
    status: "New",
    lastActivity: "Yesterday",
    capturedOn: "May 25, 2025 · 4:15 PM",
    activities: [],
  },
  {
    id: "5",
    name: "David Park",
    email: "david.park@email.com",
    phone: "+1 (555) 777-8899",
    initials: "DP",
    avatarColor: "#f97316",
    location: "Seattle, WA",
    summary: "Converted to Pro plan after 2-week trial. Annual contract.",
    source: "LinkedIn",
    agentName: "Lead Qualification Agent",
    agentRole: "Sales",
    leadScore: 88,
    status: "Converted",
    lastActivity: "2 days ago",
    capturedOn: "May 10, 2025 · 9:00 AM",
    assignedTo: "Alex M.",
    activities: [],
  },
  {
    id: "6",
    name: "Lisa Chen",
    email: "lisa.chen@email.com",
    phone: "+1 (555) 333-4455",
    initials: "LC",
    avatarColor: "#14b8a6",
    location: "San Francisco, CA",
    summary: "Inquired about commercial office space. Budget not disclosed.",
    source: "WhatsApp",
    agentName: "Real Estate Outreach Agent",
    agentRole: "Lead Generation",
    leadScore: 71,
    status: "Qualified",
    lastActivity: "3 days ago",
    capturedOn: "May 22, 2025 · 1:20 PM",
    activities: [],
  },
  {
    id: "7",
    name: "Michael Brown",
    email: "m.brown@email.com",
    phone: "+1 (555) 222-3344",
    initials: "MB",
    avatarColor: "#6366f1",
    location: "Chicago, IL",
    summary: "Lost interest after pricing discussion. May revisit in Q3.",
    source: "Email",
    agentName: "E-Commerce Support Agent",
    agentRole: "Support",
    leadScore: 42,
    status: "Lost",
    lastActivity: "1 week ago",
    capturedOn: "May 15, 2025 · 10:30 AM",
    activities: [],
  },
  {
    id: "8",
    name: "Anna Wilson",
    email: "anna.w@email.com",
    phone: "+1 (555) 666-7788",
    initials: "AW",
    avatarColor: "#a855f7",
    location: "Boston, MA",
    summary: "First-time homebuyer. Pre-approved for $280K mortgage.",
    source: "Web",
    agentName: "Real Estate Outreach Agent",
    agentRole: "Lead Generation",
    leadScore: 75,
    status: "In Progress",
    lastActivity: "4 days ago",
    capturedOn: "May 20, 2025 · 3:45 PM",
    assignedTo: "Sajam J.",
    activities: [],
  },
];

export const SOURCE_ICONS = {
  WhatsApp: MessageCircle,
  Instagram: Sparkles,
  Email: Mail,
  Web: Home,
  LinkedIn: Users,
} as const;

export const SOURCE_COLORS: Record<string, string> = {
  WhatsApp: "#22c55e",
  Instagram: "#ec4899",
  Email: "#3b82f6",
  Web: "#7c3aed",
  LinkedIn: "#0ea5e9",
};

export const SORT_OPTIONS = [
  { value: "newest", label: "Newest First" },
  { value: "oldest", label: "Oldest First" },
  { value: "score", label: "Lead Score" },
] as const;
