import {
  CheckSquare,
  FileText,
  MessageCircle,
  Send,
  Timer,
} from "lucide-react";
import type { TemplateMetric } from "./types";

export const TEMPLATE_METRICS: TemplateMetric[] = [
  {
    id: "total",
    label: "Total Templates",
    value: 48,
    trend: 12,
    trendDirection: "up",
    trendLabel: "vs last month",
    icon: FileText,
    iconBg: "#ede9fe",
    iconColor: "#7c3aed",
  },
  {
    id: "message",
    label: "Message",
    value: 18,
    trend: 8,
    trendDirection: "up",
    trendLabel: "vs last month",
    icon: MessageCircle,
    iconBg: "#dbeafe",
    iconColor: "#3b82f6",
  },
  {
    id: "pitch",
    label: "Pitch",
    value: 12,
    trend: 5,
    trendDirection: "down",
    trendLabel: "vs last month",
    icon: Send,
    iconBg: "#fef3c7",
    iconColor: "#f59e0b",
  },
  {
    id: "follow-up",
    label: "Follow Up",
    value: 10,
    trend: 15,
    trendDirection: "up",
    trendLabel: "vs last month",
    icon: Timer,
    iconBg: "#dcfce7",
    iconColor: "#22c55e",
  },
  {
    id: "task",
    label: "Task",
    value: 8,
    trend: 3,
    trendDirection: "up",
    trendLabel: "vs last month",
    icon: CheckSquare,
    iconBg: "#e0e7ff",
    iconColor: "#6366f1",
  },
];
