import type { Agency } from "./types";

export const AGENCIES: Agency[] = [
  // ───────────────── USA ─────────────────
  {
    id: 1, country: "USA", name: "Ubiquitous", ceo: "Matt Ziel",
    website: "ubiquitous.io",
    linkedin: "https://www.linkedin.com/company/ubiquitous-influencer-marketing",
    ceoLinkedin: "https://www.linkedin.com/in/mattziel",
    emailHint: "matt@ubiquitous.io", focus: "TikTok / Instagram / YouTube", size: "10–50",
  },
  {
    id: 2, country: "USA", name: "Viral Nation", ceo: "Joe Gagliese",
    website: "viralnation.com",
    linkedin: "https://www.linkedin.com/company/viral-nation",
    ceoLinkedin: "https://www.linkedin.com/in/joegagliese",
    emailHint: "joe@viralnation.com", focus: "Global Social Commerce", size: "50+",
  },
  {
    id: 3, country: "USA", name: "HireInfluence", ceo: "Christopher Jacks",
    website: "hireinfluence.com",
    linkedin: "https://www.linkedin.com/company/hireinfluence",
    ceoLinkedin: "https://www.linkedin.com/in/christopherjacks",
    emailHint: "hello@hireinfluence.com", focus: "Experiential / Fortune 1000", size: "10–50",
  },
  {
    id: 4, country: "USA", name: "Linqia", ceo: "Dan Weinstein",
    website: "linqia.com",
    linkedin: "https://www.linkedin.com/company/linqia",
    ceoLinkedin: "https://www.linkedin.com/in/danweinstein1",
    emailHint: "dan.weinstein@linqia.com", focus: "Data-Driven / Fortune 500", size: "50+",
  },
  {
    id: 5, country: "USA", name: "Carusele", ceo: "Jim Tobin",
    website: "carusele.com",
    linkedin: "https://www.linkedin.com/company/carusele",
    ceoLinkedin: "https://www.linkedin.com/in/jimtobin",
    emailHint: "jim@carusele.com", focus: "Real-Time Optimization", size: "1–10",
  },
  {
    id: 6, country: "USA", name: "The Sulfur Group", ceo: "Jon Davids",
    website: "thesulfurgroup.com",
    linkedin: "https://www.linkedin.com/company/the-sulfur-group",
    ceoLinkedin: "https://www.linkedin.com/in/jondavids",
    emailHint: "hello@thesulfurgroup.com", focus: "Short-Form / UGC Performance", size: "10–50",
  },
  {
    id: 7, country: "USA", name: "Trevant (AdParlor)", ceo: "David Gasparyan",
    website: "trevant.com",
    linkedin: "https://www.linkedin.com/company/adparlor",
    ceoLinkedin: "https://www.linkedin.com/in/davidgasparyan",
    emailHint: "info@trevant.com", focus: "Creator + Paid Media Full-Funnel", size: "10–50",
  },
  {
    id: 8, country: "USA", name: "Clicks Talent", ceo: "Lior Eldan",
    website: "clickstalent.com",
    linkedin: "https://www.linkedin.com/company/clicks-talent",
    ceoLinkedin: "https://www.linkedin.com/in/lioreldan",
    emailHint: "contact@clickstalent.com", focus: "TikTok / Global Creator Network", size: "10–50",
  },
  {
    id: 9, country: "USA", name: "SmartSites", ceo: "Alex Melen",
    website: "smartsites.com",
    linkedin: "https://www.linkedin.com/company/smartsites",
    ceoLinkedin: "https://www.linkedin.com/in/alexmelen",
    emailHint: "alex@smartsites.com", focus: "SMB Full-Service", size: "50+",
  },
  {
    id: 10, country: "USA", name: "The Shelf", ceo: "Randi Zuckerberg",
    website: "theshelf.com",
    linkedin: "https://www.linkedin.com/company/the-shelf",
    ceoLinkedin: "https://www.linkedin.com/search/results/people/?keywords=the+shelf+influencer+ceo",
    emailHint: "hello@theshelf.com", focus: "Interest Graph / ML-Powered", size: "10–50",
  },
  {
    id: 11, country: "USA", name: "Moburst", ceo: "Gilad Bechar",
    website: "moburst.com",
    linkedin: "https://www.linkedin.com/company/moburst",
    ceoLinkedin: "https://www.linkedin.com/in/giladbechar",
    emailHint: "gilad@moburst.com", focus: "Mobile / App Performance", size: "50+",
  },
  {
    id: 12, country: "USA", name: "Open Influence", ceo: "Eric Dahan",
    website: "openinfluence.com",
    linkedin: "https://www.linkedin.com/company/open-influence",
    ceoLinkedin: "https://www.linkedin.com/in/ericdahan",
    emailHint: "eric@openinfluence.com", focus: "AI-Powered Influencer Discovery", size: "50+",
  },
  {
    id: 13, country: "USA", name: "The Motherhood", ceo: "Cooper Munroe",
    website: "themotherhood.com",
    linkedin: "https://www.linkedin.com/company/the-motherhood",
    ceoLinkedin: "https://www.linkedin.com/in/coopermunroe",
    emailHint: "cooper@themotherhood.com", focus: "Family / Parenting / Lifestyle", size: "10–50",
  },
  {
    id: 14, country: "USA", name: "MOMENTiQ", ceo: "Alex Elsea",
    website: "momentiq.com",
    linkedin: "https://www.linkedin.com/company/momentiq",
    ceoLinkedin: "https://www.linkedin.com/in/alexelsea",
    emailHint: "alex@momentiq.com", focus: "Enterprise / Live Shopping", size: "10–50",
  },
  {
    id: 15, country: "USA", name: "Fresh Content Society", ceo: "Erik Huberman",
    website: "freshcontentsociety.com",
    linkedin: "https://www.linkedin.com/company/fresh-content-society",
    ceoLinkedin: "https://www.linkedin.com/in/erikhuberman",
    emailHint: "hello@freshcontentsociety.com", focus: "Mid-Market / Enterprise", size: "10–50",
  },
  {
    id: 16, country: "USA", name: "Sway Group", ceo: "Danielle Wiley",
    website: "swaygroup.com",
    linkedin: "https://www.linkedin.com/company/sway-group",
    ceoLinkedin: "https://www.linkedin.com/in/daniellewiley",
    emailHint: "dwiley@swaygroup.com", focus: "Large Brand / Multi-Platform", size: "10–50",
  },
  {
    id: 17, country: "USA", name: "Station Entertainment", ceo: "Brendan Gahan",
    website: "stationentertainment.com",
    linkedin: "https://www.linkedin.com/company/station-entertainment",
    ceoLinkedin: "https://www.linkedin.com/in/brendangahan",
    emailHint: "info@stationentertainment.com", focus: "YouTube / SMB", size: "10–50",
  },
  {
    id: 18, country: "USA", name: "Whalar Group", ceo: "Neil Waller",
    website: "whalar.com",
    linkedin: "https://www.linkedin.com/company/whalar",
    ceoLinkedin: "https://www.linkedin.com/in/neilwaller",
    emailHint: "hello@whalar.com", focus: "Creator Economy / Brand Partnerships", size: "50+",
  },

  // ───────────────── UK ─────────────────
  {
    id: 19, country: "UK", name: "The Goat Agency", ceo: "Nick Cooke",
    website: "thegoatagency.com",
    linkedin: "https://www.linkedin.com/company/the-goat-agency",
    ceoLinkedin: "https://www.linkedin.com/in/nickcooke",
    emailHint: "hello@thegoatagency.com", focus: "Global Multi-Market / 37 Countries", size: "50+",
  },
  {
    id: 20, country: "UK", name: "House of Marketers", ceo: "Inigo Rivero",
    website: "houseofmarketers.com",
    linkedin: "https://www.linkedin.com/company/house-of-marketers",
    ceoLinkedin: "https://www.linkedin.com/in/inigorivero",
    emailHint: "inigo@houseofmarketers.com", focus: "TikTok Specialist / Global", size: "10–50",
  },
  {
    id: 21, country: "UK", name: "Anicca Digital", ceo: "Ann Stanley",
    website: "aniccadigital.co.uk",
    linkedin: "https://www.linkedin.com/company/anicca-digital",
    ceoLinkedin: "https://www.linkedin.com/in/annstanley",
    emailHint: "hello@aniccadigital.co.uk", focus: "B2B & B2C / Multi-Channel", size: "10–50",
  },
  {
    id: 22, country: "UK", name: "Billion Dollar Boy", ceo: "Edward East",
    website: "billiondollarboy.com",
    linkedin: "https://www.linkedin.com/company/billion-dollar-boy",
    ceoLinkedin: "https://www.linkedin.com/in/edwardeast",
    emailHint: "hello@billiondollarboy.com", focus: "Creator Commerce / Fashion & Beauty", size: "50+",
  },
  {
    id: 23, country: "UK", name: "The Social Shepherd", ceo: "Jack Shepherd",
    website: "thesocialshepherd.com",
    linkedin: "https://www.linkedin.com/company/the-social-shepherd",
    ceoLinkedin: "https://www.linkedin.com/in/jackshepherd1",
    emailHint: "jack@thesocialshepherd.com", focus: "US & UK / Paid Social + Influencer", size: "10–50",
  },
  {
    id: 24, country: "UK", name: "Jungle Creations", ceo: "Jamie Bolding",
    website: "junglecreations.com",
    linkedin: "https://www.linkedin.com/company/jungle-creations",
    ceoLinkedin: "https://www.linkedin.com/in/jamiembolding",
    emailHint: "hello@junglecreations.com", focus: "Content Studio / Social Brands", size: "50+",
  },
  {
    id: 25, country: "UK", name: "Influencer (Agency)", ceo: "Ben Jeffries",
    website: "influencer.com",
    linkedin: "https://www.linkedin.com/company/influencer",
    ceoLinkedin: "https://www.linkedin.com/in/benjeffries",
    emailHint: "ben@influencer.com", focus: "Enterprise / Talent Marketplace", size: "50+",
  },
  {
    id: 26, country: "UK", name: "Socially Powerful", ceo: "Percy Butcher",
    website: "sociallypowerful.com",
    linkedin: "https://www.linkedin.com/company/socially-powerful",
    ceoLinkedin: "https://www.linkedin.com/in/percybutcher",
    emailHint: "hello@sociallypowerful.com", focus: "Global / Gaming / Fashion", size: "10–50",
  },
  {
    id: 27, country: "UK", name: "Obviously", ceo: "Mae Karwowski",
    website: "obvious.ly",
    linkedin: "https://www.linkedin.com/company/obviously-inc",
    ceoLinkedin: "https://www.linkedin.com/in/maekarwowski",
    emailHint: "mae@obvious.ly", focus: "CPG / Lifestyle / Mass Scale", size: "10–50",
  },
  {
    id: 28, country: "UK", name: "Favoured", ceo: "Ben Wooltorton",
    website: "favoured.online",
    linkedin: "https://www.linkedin.com/company/favoured",
    ceoLinkedin: "https://www.linkedin.com/in/benwooltorton",
    emailHint: "hello@favoured.online", focus: "Fintech / eCommerce / Performance", size: "10–50",
  },
  {
    id: 29, country: "UK", name: "Disrupt Marketing", ceo: "Joe Lenehan",
    website: "disruptmarketing.co.uk",
    linkedin: "https://www.linkedin.com/company/disrupt-marketing",
    ceoLinkedin: "https://www.linkedin.com/in/joelenehan",
    emailHint: "hello@disruptmarketing.co.uk", focus: "Fashion / Beauty / Lifestyle", size: "10–50",
  },
  {
    id: 30, country: "UK", name: "Seen Connects", ceo: "Paul Archer",
    website: "seenconnects.com",
    linkedin: "https://www.linkedin.com/company/seen-connects",
    ceoLinkedin: "https://www.linkedin.com/in/paularcherlondon",
    emailHint: "hello@seenconnects.com", focus: "Ambassador Programs / Global", size: "10–50",
  },

  // ───────────────── UAE ─────────────────
  {
    id: 31, country: "UAE", name: "inHype", ceo: "Bader Al-Sallal",
    website: "inhype.ae",
    linkedin: "https://www.linkedin.com/company/inhypeagency",
    ceoLinkedin: "https://www.linkedin.com/company/inhypeagency",
    emailHint: "hello@inhype.ae", focus: "FMCG / Beauty / Retail (UAE + KSA)", size: "10–50",
  },
  {
    id: 32, country: "UAE", name: "Amplify Dubai", ceo: "Jonathan Emmins",
    website: "amplifyuk.net",
    linkedin: "https://www.linkedin.com/company/amplify",
    ceoLinkedin: "https://www.linkedin.com/in/jonathanemins",
    emailHint: "hello@amplifyuk.net", focus: "Experiential / Brand Events", size: "50+",
  },
  {
    id: 33, country: "UAE", name: "GIMA Agency", ceo: "Founder (Search LinkedIn)",
    website: "gimaagency.com",
    linkedin: "https://www.linkedin.com/search/results/companies/?keywords=GIMA+influencer+UAE",
    ceoLinkedin: "https://www.linkedin.com/search/results/people/?keywords=GIMA+agency+dubai",
    emailHint: "info@gimaagency.com", focus: "ROI Campaigns / MENA", size: "10–50",
  },
  {
    id: 34, country: "UAE", name: "Videaze", ceo: "Founder (Search LinkedIn)",
    website: "videaze.com",
    linkedin: "https://www.linkedin.com/search/results/companies/?keywords=Videaze+UAE",
    ceoLinkedin: "https://www.linkedin.com/search/results/people/?keywords=Videaze+agency+founder",
    emailHint: "hello@videaze.com", focus: "Video Content / GCC Region", size: "1–10",
  },
  {
    id: 35, country: "UAE", name: "Grynow (MENA)", ceo: "Vaibhav Gupta",
    website: "grynow.in",
    linkedin: "https://www.linkedin.com/company/grynow",
    ceoLinkedin: "https://www.linkedin.com/in/vaibhavgupta-grynow",
    emailHint: "hello@grynow.in", focus: "Creator Network / Tech-Enabled", size: "10–50",
  },
  {
    id: 36, country: "UAE", name: "247 Agency Dubai", ceo: "Founder (Search LinkedIn)",
    website: "247.ae",
    linkedin: "https://www.linkedin.com/company/247-agency",
    ceoLinkedin: "https://www.linkedin.com/search/results/people/?keywords=247+agency+dubai+founder",
    emailHint: "info@247.ae", focus: "Brand Strategy / Performance / GCC", size: "10–50",
  },
  {
    id: 37, country: "UAE", name: "ViralMango", ceo: "Founder (Search LinkedIn)",
    website: "viralmango.ae",
    linkedin: "https://www.linkedin.com/company/viralmango",
    ceoLinkedin: "https://www.linkedin.com/search/results/people/?keywords=ViralMango+Dubai+CEO",
    emailHint: "hello@viralmango.ae", focus: "Micro-Influencers / UAE Brands", size: "1–10",
  },
  {
    id: 38, country: "UAE", name: "Digital Nexa", ceo: "Andrew Thomas",
    website: "wearenexa.com",
    linkedin: "https://www.linkedin.com/company/digitalnexa",
    ceoLinkedin: "https://www.linkedin.com/in/andrew-thomas-nexa",
    emailHint: "andrew@wearenexa.com", focus: "HubSpot Partner / Full-Service", size: "10–50",
  },
  {
    id: 39, country: "UAE", name: "Prism Dubai", ceo: "Founder (Search LinkedIn)",
    website: "prismdubai.com",
    linkedin: "https://www.linkedin.com/company/prism-middle-east",
    ceoLinkedin: "https://www.linkedin.com/search/results/people/?keywords=Prism+Dubai+founder+CEO",
    emailHint: "info@prismdubai.com", focus: "PR + Influencer / Luxury", size: "10–50",
  },
  {
    id: 40, country: "UAE", name: "Traffic Digital", ceo: "Carl Franzen",
    website: "trafficdigital.net",
    linkedin: "https://www.linkedin.com/company/traffic-digital",
    ceoLinkedin: "https://www.linkedin.com/in/carlfranzen",
    emailHint: "carl@trafficdigital.net", focus: "Full-Service / MENA Growth", size: "50+",
  },
  {
    id: 41, country: "UAE", name: "Chain Reaction", ceo: "Firas Murr",
    website: "chainreaction.ae",
    linkedin: "https://www.linkedin.com/company/chain-reaction-ksa",
    ceoLinkedin: "https://www.linkedin.com/in/firasmurr",
    emailHint: "hello@chainreaction.ae", focus: "SEO + Social / Saudi & UAE", size: "10–50",
  },
  {
    id: 42, country: "UAE", name: "Flip Media", ceo: "Founder (Search LinkedIn)",
    website: "flipmedia.ae",
    linkedin: "https://www.linkedin.com/company/flip-media",
    ceoLinkedin: "https://www.linkedin.com/search/results/people/?keywords=Flip+Media+Dubai+founder",
    emailHint: "hello@flipmedia.ae", focus: "Social Media / Influencer / UAE", size: "10–50",
  },

  // ───────────────── Australia ─────────────────
  {
    id: 43, country: "Australia", name: "Hoozu", ceo: "Nathan Ruff",
    website: "hoozu.com",
    linkedin: "https://www.linkedin.com/company/hoozu",
    ceoLinkedin: "https://www.linkedin.com/in/nathanruff",
    emailHint: "hello@hoozu.com", focus: "Human Media / Creator Campaigns", size: "10–50",
  },
  {
    id: 44, country: "Australia", name: "Megaphone Marketing", ceo: "Lauren Oakes",
    website: "megaphonemarketing.com.au",
    linkedin: "https://www.linkedin.com/company/megaphone-marketing",
    ceoLinkedin: "https://www.linkedin.com/in/laurenoakes",
    emailHint: "lauren@megaphonemarketing.com.au", focus: "Meta + Influencer / eCommerce", size: "10–50",
  },
  {
    id: 45, country: "Australia", name: "Social Soup", ceo: "Sharyn Smith",
    website: "socialsoup.com.au",
    linkedin: "https://www.linkedin.com/company/social-soup",
    ceoLinkedin: "https://www.linkedin.com/in/sharynsmith",
    emailHint: "sharyn@socialsoup.com.au", focus: "Micro & Nano Influencer Pioneer", size: "10–50",
  },
  {
    id: 46, country: "Australia", name: "The Natives", ceo: "Victoria Tynan",
    website: "thenatives.com.au",
    linkedin: "https://www.linkedin.com/company/the-natives",
    ceoLinkedin: "https://www.linkedin.com/in/victoriatynan",
    emailHint: "hello@thenatives.com.au", focus: "Lifestyle / Beauty / Wellness", size: "10–50",
  },
  {
    id: 47, country: "Australia", name: "Vamp", ceo: "Aaron Brooks",
    website: "vamp.io",
    linkedin: "https://www.linkedin.com/company/vampit",
    ceoLinkedin: "https://www.linkedin.com/in/aaronbrooks",
    emailHint: "hello@vamp.io", focus: "Creator Platform / Global Network", size: "10–50",
  },
  {
    id: 48, country: "Australia", name: "Hypetap", ceo: "Detch Singh",
    website: "hypetap.com",
    linkedin: "https://www.linkedin.com/company/hypetap",
    ceoLinkedin: "https://www.linkedin.com/in/detchsingh",
    emailHint: "hello@hypetap.com", focus: "SaaS + Managed Campaigns", size: "10–50",
  },
  {
    id: 49, country: "Australia", name: "Disruptive Digital", ceo: "Andrew Bogoyev",
    website: "disruptivedigital.com.au",
    linkedin: "https://www.linkedin.com/company/disruptive-digital-australia",
    ceoLinkedin: "https://www.linkedin.com/in/andrewbogoyev",
    emailHint: "andrew@disruptivedigital.com.au", focus: "Social Strategy / Performance", size: "10–50",
  },
  {
    id: 50, country: "Australia", name: "The Influence Group", ceo: "Founder (Search LinkedIn)",
    website: "theinfluencegroup.com.au",
    linkedin: "https://www.linkedin.com/search/results/companies/?keywords=influence+group+australia",
    ceoLinkedin: "https://www.linkedin.com/search/results/people/?keywords=influence+group+australia+founder",
    emailHint: "hello@theinfluencegroup.com.au", focus: "B2B + B2C / ANZ", size: "1–10",
  },
  {
    id: 51, country: "Australia", name: "Emote Digital", ceo: "Founder (Search LinkedIn)",
    website: "emotedigital.com.au",
    linkedin: "https://www.linkedin.com/company/emote-digital",
    ceoLinkedin: "https://www.linkedin.com/search/results/people/?keywords=emote+digital+australia+founder",
    emailHint: "hello@emotedigital.com.au", focus: "Branding + Social / Melbourne", size: "10–50",
  },
  {
    id: 52, country: "Australia", name: "Frank Body (Acquired Influence)", ceo: "Steve Rowley",
    website: "wegrowbrands.com.au",
    linkedin: "https://www.linkedin.com/company/we-grow-brands",
    ceoLinkedin: "https://www.linkedin.com/in/steverowley",
    emailHint: "hello@wegrowbrands.com.au", focus: "eCommerce / Beauty / Wellness", size: "1–10",
  },
];
